name: sushi

on: [push]
jobs:
  lint:
    name: Sushi arkhn template
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install modules
        run: npm install -g fsh-sushi
      - name: Run sushi
        run: sushi .
      - name: Check version change on package-list
        run: exit $([ ! -z "$(git diff package-list.json | grep version)" ] && echo 1 || echo 0)
      - name: Check version change on sushi-config
        run: exit $([ -z "$(git diff sushi-config.yaml | grep version)" ] && echo 1 || echo 0)
